FROM node:14.21.3-slim

RUN apt-get update && \
    apt-get install -y \
        net-tools \
        iputils-ping \
        telnet \
        python2 \
        build-essential

# Clean up
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*